name: Playwright Test

on: [deployment_status]

jobs:
  print_preview_url:
    name: Playwright Tests
    runs-on: ubuntu-latest
    if: ${{ github.event.deployment_status.state == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Print preview url
        env:
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        run: |
          echo '${{ github.event.deployment_status.target_url }}'
